"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
[](bg:#94e2d5 fg:#a3aed2)\
$directory\
[](bg:#394260 fg:#94e2d5)\
$git_branch\
$git_status\
[](fg:#394260)\
\n$character"""

[username]
show_always = true
format = "[ $user ](bg:#a3aed2 fg:#090c0c)"

[directory]
style = "bg:#94e2d5 fg:#090c0c"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](bg:#394260 fg:#94e2d5)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](bg:#394260 fg:#94e2d5)]($style)'

[character]
success_symbol = "[╰─>](fg:#94e2d5)"
error_symbol = "[TEST > ](fg:red)"
