"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭─ ](secondary)$username\
$hostname\
[ in](bold secondary)\
$directory\
$fill\
$git_branch\
$git_status\
\n$character"""

palette = 'mytheme'

[palettes.mytheme]
main = '#8aadf4'
secondary = '#94e2d5'

[username]
show_always = true
format = "[$user](bold main)"

[hostname]
ssh_only = false
format = "[@$hostname](bold main)"

[directory]
style = "bold main"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[fill]
symbol = "."
style = "bold secondary"

[git_branch]
symbol = ""
style = "bold main"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bold main"
format = '[($all_status$ahead_behind )]($style)'

[character]
success_symbol = "[╰─>](bold secondary)"
error_symbol = "[╰─>](bold secondary)"
